# rules.py — maps Windows Security event IDs to triage decisions.
#
# Each rule looks at a normalised event dict and, if the event matches a known
# security pattern, appends a "hit" dict to the results list.  Multiple rules
# can fire on the same event.
#
# A hit dict contains:
#   rule_id  — a stable identifier (never reused) so hits can be tracked over time
#   name     — short human-readable label
#   effect   — priority signal consumed by scoring.py
#               ("critical" > "high_priority" > "medium_priority" > "review" >
#                "baseline" > "deprioritise")
#   reason   — plain-English explanation shown to the analyst

from typing import Dict, List

# Account name prefixes that belong to built-in Windows service identities.
# Logons from these accounts are typically automated and not analyst-actionable.
SYSTEM_LIKE_PREFIXES = ("SYSTEM", "DWM-", "UMFD-")


def _is_system_noise(event: Dict) -> bool:
    """Return True if this event was generated by a built-in Windows service account.

    Windows constantly creates logon events for its own internal processes
    (e.g. Desktop Window Manager, User-Mode Font Driver).  Flagging them as noise
    keeps the analyst queue free of irrelevant entries.
    """
    account = (event.get("new_logon_account") or event.get("subject_account") or "").upper()
    logon_type = event.get("logon_type")
    return (
        account.startswith(SYSTEM_LIKE_PREFIXES)
        or (account == "SYSTEM")
        or (logon_type == "5" and account == "SYSTEM")  # logon type 5 = service logon
    )


def evaluate_event(event: Dict) -> List[Dict]:
    """Check a normalised event against all known rules and return a list of rule hits.

    Rules are evaluated top-to-bottom.  An event can match more than one rule —
    for example it might be both system noise (R001) and match no other rule (R999).
    scoring.py picks the highest-severity effect from the combined hit list.

    If no specific rule matches, R999 is appended so every event has at least one hit
    and is retained for manual review rather than silently dropped.
    """
    hits: List[Dict] = []
    event_id = event.get("event_id")

    # Determine the most relevant account name for this event type.
    # new_logon_account is set on successful logons (4624),
    # target_account is set on failed logons (4625),
    # subject_account is the fallback (e.g. for privilege events like 4672).
    account = (
        event.get("new_logon_account")
        or event.get("target_account")
        or event.get("subject_account")
    )

    # R001 — suppress routine Windows service logons so they don't clutter the queue.
    if _is_system_noise(event):
        hits.append({
            "rule_id": "R001",
            "name": "System noise / service logon",
            "effect": "deprioritise",
            "reason": "System, DWM, UMFD, or service-driven logon identified."
        })

    # R010 — a successful interactive (keyboard/screen) logon by a known test account.
    # Event 4624 = successful logon; logon type "2" = interactive.
    if event_id == 4624 and event.get("logon_type") == "2" and account and str(account).lower().startswith("testuser"):
        hits.append({
            "rule_id": "R010",
            "name": "Interactive standard-user logon",
            "effect": "baseline",
            "reason": "Successful interactive logon by a non-admin test account."
        })

    # R020 — any failed logon attempt.
    # Event 4625 is generated whenever Windows rejects a logon for any reason
    # (wrong password, disabled account, etc.).  Even a single failure warrants a look.
    if event_id == 4625:
        hits.append({
            "rule_id": "R020",
            "name": "Failed interactive logon",
            "effect": "review",
            "reason": "Failed logon detected; requires authentication review."
        })

    # R030 — special privileges assigned to a named admin account.
    # Event 4672 fires when an account logs on with elevated privileges such as
    # SeDebugPrivilege or SeTcbPrivilege.  Restricted here to the 'labadmin' account.
    if event_id == 4672 and (event.get("subject_account") or "").lower() == "labadmin":
        hits.append({
            "rule_id": "R030",
            "name": "Privileged logon",
            "effect": "high_priority",
            "reason": "Special privileges assigned to labadmin."
        })

    # R040 — a new local user account was created.
    # Event 4720 is a key indicator of potential persistence (attacker adding a backdoor user).
    if event_id == 4720:
        hits.append({
            "rule_id": "R040",
            "name": "User account created",
            "effect": "high_priority",
            "reason": "Creation of a local account is security-relevant."
        })

    # R050 — a local user account was deleted.
    # Event 4726 can indicate an attacker cleaning up after themselves, or an admin error.
    if event_id == 4726:
        hits.append({
            "rule_id": "R050",
            "name": "User account deleted",
            "effect": "high_priority",
            "reason": "Deletion of a local account is security-relevant."
        })

    # R060 — a user was added to a security-enabled local group (e.g. Administrators).
    # Event 4732 is a high-fidelity privilege-escalation indicator.
    if event_id == 4732:
        hits.append({
            "rule_id": "R060",
            "name": "Added to security-enabled local group",
            "effect": "high_priority",
            "reason": "Group-membership expansion can indicate privilege escalation."
        })

    # R070 — a user was removed from a security-enabled local group.
    # Event 4733 is lower risk than addition but still worth reviewing.
    if event_id == 4733:
        hits.append({
            "rule_id": "R070",
            "name": "Removed from security-enabled local group",
            "effect": "medium_priority",
            "reason": "Group-membership removal may still warrant review."
        })

    # R080 — the Security audit log was cleared.
    # Event 1102 is almost always malicious: attackers clear logs to hide their tracks.
    if event_id == 1102:
        hits.append({
            "rule_id": "R080",
            "name": "Security log cleared",
            "effect": "critical",
            "reason": "Clearing the audit log is a high-risk event."
        })

    # R999 — catch-all for events that matched no specific rule above.
    # Keeps the event visible in the output so analysts can decide whether a new
    # rule should be written for it.
    if not hits:
        hits.append({
            "rule_id": "R999",
            "name": "No specific rule matched",
            "effect": "review",
            "reason": "Event retained for manual review pending rule expansion."
        })

    return hits
